-- =====================================================================
-- PART 2 of 2 — permissions, auth functions and locations
-- Generated by supabase/scripts/build-setup-files.sh — do not edit.
-- Paste into the Supabase SQL Editor and run. Run after Part 1 succeeds.
-- =====================================================================

-- ---------- 0019_role_permission_matrix.sql ----------
-- =====================================================================
-- 0019_role_permission_matrix.sql — PHASE 1 (part 2)
--
-- Separate file because Postgres refuses to use an enum value added by
-- `ALTER TYPE ... ADD VALUE` in the same transaction that added it. Splitting
-- the migration is the documented workaround and is safer than hoping the
-- statements land in different transactions.
-- =====================================================================

insert into role_permissions (role, permission) values
  -- Super admin: everything, including the ability to change roles.
  ('super_admin','listings.read.all'), ('super_admin','listings.publish'),
  ('super_admin','listings.moderate'), ('super_admin','bookings.read.all'),
  ('super_admin','bookings.manage'), ('super_admin','payments.read'),
  ('super_admin','payments.refund'), ('super_admin','content.write'),
  ('super_admin','content.publish'), ('super_admin','reviews.moderate'),
  ('super_admin','leads.read'), ('super_admin','leads.manage'),
  ('super_admin','support.impersonate'), ('super_admin','users.read'),
  ('super_admin','users.suspend'), ('super_admin','users.assign_roles'),
  ('super_admin','businesses.approve'), ('super_admin','settings.write'),
  ('super_admin','analytics.read'),

  -- Admin: everything operational, but NOT role assignment. Only a super
  -- admin can create another admin — otherwise the highest privilege on the
  -- platform is self-replicating.
  ('admin','listings.read.all'), ('admin','listings.publish'),
  ('admin','listings.moderate'), ('admin','bookings.read.all'),
  ('admin','bookings.manage'), ('admin','payments.read'),
  ('admin','payments.refund'), ('admin','content.write'),
  ('admin','content.publish'), ('admin','reviews.moderate'),
  ('admin','leads.read'), ('admin','leads.manage'),
  ('admin','support.impersonate'), ('admin','users.read'),
  ('admin','users.suspend'), ('admin','businesses.approve'),
  ('admin','settings.write'), ('admin','analytics.read'),

  -- Content manager: the site's words and pages. No money, no accounts.
  ('content_manager','content.write'), ('content_manager','content.publish'),
  ('content_manager','listings.read.all'), ('content_manager','reviews.moderate'),
  ('content_manager','settings.write'),

  -- Booking manager: the transactional desk. Can refund, cannot publish.
  ('booking_manager','bookings.read.all'), ('booking_manager','bookings.manage'),
  ('booking_manager','payments.read'), ('booking_manager','payments.refund'),
  ('booking_manager','listings.read.all'), ('booking_manager','leads.read'),

  -- Support agent: read widely, change little. Impersonation is logged.
  ('support_agent','bookings.read.all'), ('support_agent','listings.read.all'),
  ('support_agent','leads.read'), ('support_agent','leads.manage'),
  ('support_agent','users.read'), ('support_agent','support.impersonate'),
  ('support_agent','reviews.moderate'),

  -- Business owner: full control of their own business, nothing beyond it.
  ('business_owner','listings.write.own'), ('business_owner','bookings.read.own'),
  ('business_owner','reviews.reply.own'), ('business_owner','payments.read'),
  ('business_owner','leads.read'),

  -- Tour operator and hotel manager are business owners scoped to a
  -- vertical. Same powers today; separate roles because their dashboards,
  -- onboarding and permissions will diverge.
  ('tour_operator','listings.write.own'), ('tour_operator','bookings.read.own'),
  ('tour_operator','reviews.reply.own'), ('tour_operator','payments.read'),
  ('tour_operator','leads.read'),

  ('hotel_manager','listings.write.own'), ('hotel_manager','bookings.read.own'),
  ('hotel_manager','reviews.reply.own'), ('hotel_manager','leads.read'),

  -- Business staff: work the listings, never see the money.
  ('business_staff','listings.write.own'), ('business_staff','bookings.read.own'),
  ('business_staff','reviews.reply.own')

  -- Customer holds NO platform permissions. Everything a customer may do is
  -- scoped to rows they own, which RLS expresses directly with auth.uid().
on conflict do nothing;

create policy permissions_read on permissions for select using (auth.uid() is not null);
create policy role_permissions_read on role_permissions for select using (auth.uid() is not null);

-- ---------- 0020_auth_functions.sql ----------
-- =====================================================================
-- 0020_auth_functions.sql — PHASE 1 (part 3): authorization helpers.
--
-- Every function here is the thing RLS policies actually call, so each is
-- `stable` and `security definer` — stable lets the planner evaluate once per
-- statement instead of once per row, which is the difference between a fast
-- policy and a table scan.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. IDENTITY
-- ---------------------------------------------------------------------
create or replace function auth_role()
returns user_role
language sql stable security definer set search_path = public
as $$
  select role from profiles where id = auth.uid();
$$;

/**
 * Whether the caller's account is usable at all.
 *
 * Deliberately separate from role. A suspended super admin must lose every
 * power immediately, and checking role alone would leave them fully
 * privileged until someone remembers to also change it.
 */
create or replace function auth_active()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from profiles
    where id = auth.uid() and status = 'active' and deleted_at is null
  );
$$;

/**
 * The single authorization primitive. Everything else is a convenience
 * wrapper around it, so there is one place to audit and one place to change.
 */
create or replace function has_permission(p_permission text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select auth_active() and exists (
    select 1 from role_permissions rp
    where rp.role = auth_role() and rp.permission = p_permission
  );
$$;

create or replace function is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select auth_active() and coalesce(auth_role() in ('admin','super_admin'), false);
$$;

create or replace function is_super_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select auth_active() and coalesce(auth_role() = 'super_admin', false);
$$;

/**
 * "Staff" now means any internal role, which is what most policies want.
 * Note the account-status gate: a suspended content manager reads nothing.
 */
create or replace function is_staff()
returns boolean
language sql stable security definer set search_path = public
as $$
  select auth_active() and coalesce(
    auth_role() in ('content_manager','booking_manager','support_agent','admin','super_admin'),
    false);
$$;

/** Business-side roles, used to decide which dashboard someone lands on. */
create or replace function is_business_user()
returns boolean
language sql stable security definer set search_path = public
as $$
  select auth_active() and coalesce(
    auth_role() in ('business_owner','business_staff','tour_operator','hotel_manager'),
    false);
$$;

create or replace function is_company_member(p_company_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select auth_active() and exists (
    select 1 from company_members cm
    where cm.company_id = p_company_id
      and cm.profile_id = auth.uid()
      and cm.accepted_at is not null
  );
$$;

-- ---------------------------------------------------------------------
-- 2. ACCOUNT LIFECYCLE
-- ---------------------------------------------------------------------

/**
 * Marks a profile verified and active once Supabase confirms the email.
 * A profile stays `pending_verification` until this runs, which is what stops
 * an unverified address from booking or reviewing.
 */
create or replace function internal.sync_email_verification()
returns trigger
language plpgsql security definer set search_path = public, auth, internal
as $$
begin
  update public.profiles p
     set email = new.email,
         email_verified_at = new.email_confirmed_at,
         status = case
           when p.status in ('suspended','banned','deactivated') then p.status
           when new.email_confirmed_at is not null then 'active'::account_status
           else 'pending_verification'::account_status
         end,
         last_login_at = coalesce(new.last_sign_in_at, p.last_login_at)
   where p.id = new.id;
  return null;
end;
$$;

drop trigger if exists on_auth_user_verified on auth.users;
create trigger on_auth_user_verified
  after update of email_confirmed_at, last_sign_in_at, email on auth.users
  for each row execute function internal.sync_email_verification();

-- Provision a profile on sign-up, now carrying email and status.
create or replace function internal.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public, internal
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, referral_code, status, email_verified_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url',
    upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 8)),
    case when new.email_confirmed_at is not null then 'active'::account_status
         else 'pending_verification'::account_status end,
    new.email_confirmed_at
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

/**
 * Role assignment. Restricted to super admins, because a role is the only
 * thing standing between an account and every booking on the platform.
 *
 * Two rules encoded here that an `update` statement could not express:
 *   - nobody may change their own role, including a super admin
 *   - the last remaining super admin cannot be demoted, or the platform
 *     locks itself out with no way back in short of direct SQL
 */
create or replace function assign_role(p_profile_id uuid, p_role user_role, p_reason text default null)
returns profiles
language plpgsql security definer set search_path = public
as $$
declare
  v_profile profiles;
  v_old     user_role;
begin
  if not is_super_admin() then
    raise exception 'Only a super admin can change roles' using errcode = 'insufficient_privilege';
  end if;
  if p_profile_id = auth.uid() then
    raise exception 'You cannot change your own role' using errcode = 'insufficient_privilege';
  end if;

  select role into v_old from profiles where id = p_profile_id;
  if not found then
    raise exception 'That account does not exist' using errcode = 'no_data_found';
  end if;

  if v_old = 'super_admin' and p_role <> 'super_admin'
     and (select count(*) from profiles where role = 'super_admin' and status = 'active') <= 1 then
    raise exception 'This is the last active super admin. Promote someone else first.'
      using errcode = 'invalid_parameter_value';
  end if;

  update profiles set role = p_role where id = p_profile_id returning * into v_profile;

  insert into audit_logs (actor_id, actor_role, action, entity_type, entity_id, before, after)
  values (auth.uid(), auth_role(), 'user.assign_role', 'profile', p_profile_id,
          jsonb_build_object('role', v_old),
          jsonb_build_object('role', p_role, 'reason', p_reason));

  return v_profile;
end;
$$;

create or replace function set_account_status(
  p_profile_id uuid, p_status account_status, p_reason text default null
)
returns profiles
language plpgsql security definer set search_path = public
as $$
declare v_profile profiles;
begin
  if not has_permission('users.suspend') then
    raise exception 'You do not have permission to change account status'
      using errcode = 'insufficient_privilege';
  end if;
  if p_profile_id = auth.uid() then
    raise exception 'You cannot change your own account status' using errcode = 'insufficient_privilege';
  end if;
  if p_status in ('suspended','banned') and coalesce(trim(p_reason), '') = '' then
    raise exception 'A reason is required when suspending an account'
      using errcode = 'invalid_parameter_value';
  end if;
  -- An admin must not be able to suspend a super admin from under them.
  if (select role from profiles where id = p_profile_id) = 'super_admin' and not is_super_admin() then
    raise exception 'Only a super admin can change another super admin'
      using errcode = 'insufficient_privilege';
  end if;

  update profiles
     set status = p_status,
         suspended_reason = case when p_status in ('suspended','banned') then p_reason else null end,
         suspended_at     = case when p_status in ('suspended','banned') then now() else null end,
         suspended_by     = case when p_status in ('suspended','banned') then auth.uid() else null end,
         deactivated_at   = case when p_status = 'deactivated' then now() else null end
   where id = p_profile_id
  returning * into v_profile;

  insert into audit_logs (actor_id, actor_role, action, entity_type, entity_id, after)
  values (auth.uid(), auth_role(), 'user.set_status', 'profile', p_profile_id,
          jsonb_build_object('status', p_status, 'reason', p_reason));

  return v_profile;
end;
$$;

-- ---------------------------------------------------------------------
-- 3. RECREATED FUNCTIONS
-- These held the old role names as text inside their bodies, which a
-- `RENAME VALUE` cannot reach.
-- ---------------------------------------------------------------------
create or replace function approve_company_application(
  p_application_id uuid, p_commission_rate numeric default 20.00, p_note text default null
)
returns companies
language plpgsql security definer set search_path = public
as $$
declare
  v_app company_applications; v_company companies; v_slug text; v_suffix integer := 0;
begin
  if not has_permission('businesses.approve') then
    raise exception 'Only an administrator can approve an application'
      using errcode = 'insufficient_privilege';
  end if;

  select * into v_app from company_applications where id = p_application_id for update;
  if not found then
    raise exception 'Application not found' using errcode = 'no_data_found';
  end if;
  if v_app.status = 'approved' then
    return (select c from companies c where c.id = v_app.company_id);
  end if;
  if v_app.status not in ('submitted','under_review','needs_info') then
    raise exception 'Cannot approve an application with status %', v_app.status
      using errcode = 'invalid_parameter_value';
  end if;

  v_slug := internal.slugify(v_app.display_name);
  while exists (select 1 from companies where slug = v_slug) loop
    v_suffix := v_suffix + 1;
    v_slug := internal.slugify(v_app.display_name) || '-' || v_suffix;
  end loop;

  insert into companies (
    slug, legal_name, display_name, status, verification, country_id, city_id,
    contact_email, contact_phone, whatsapp, website, about,
    trade_license_no, trade_license_url, tax_registration_no,
    commission_rate, payout_currency, onboarded_at
  )
  select v_slug, v_app.legal_name, v_app.display_name, 'active', 'verified',
         v_app.country_id, v_app.city_id, v_app.contact_email, v_app.contact_phone,
         v_app.whatsapp, v_app.website, v_app.about,
         v_app.trade_license_no, v_app.trade_license_url, v_app.tax_registration_no,
         p_commission_rate, c.currency, now()
  from countries c where c.id = v_app.country_id
  returning * into v_company;

  insert into company_members (company_id, profile_id, role, permissions, accepted_at)
  values (v_company.id, v_app.submitted_by, 'business_owner',
          array['listings.write.own','bookings.read.own','payments.read','reviews.reply.own'], now());

  -- Only promote a plain customer. An admin who also runs a tour company must
  -- not be demoted by approving their own application.
  update profiles set role = 'business_owner'
   where id = v_app.submitted_by and role = 'customer';

  update company_applications
     set status = 'approved', company_id = v_company.id,
         reviewed_by = auth.uid(), reviewed_at = now(), review_notes = p_note
   where id = p_application_id;

  insert into audit_logs (actor_id, actor_role, action, entity_type, entity_id, after)
  values (auth.uid(), auth_role(), 'company_application.approve', 'company', v_company.id,
          jsonb_build_object('application_id', p_application_id, 'slug', v_slug,
                             'commission_rate', p_commission_rate));
  return v_company;
end;
$$;

create or replace function approve_listing_claim(p_claim_id uuid, p_note text default null)
returns listing_claims
language plpgsql security definer set search_path = public
as $$
declare v_claim listing_claims;
begin
  if not has_permission('businesses.approve') then
    raise exception 'Only an administrator can approve a claim' using errcode = 'insufficient_privilege';
  end if;

  select * into v_claim from listing_claims where id = p_claim_id for update;
  if not found then
    raise exception 'Claim not found' using errcode = 'no_data_found';
  end if;
  if v_claim.status = 'approved' then return v_claim; end if;

  insert into company_members (company_id, profile_id, role, permissions, accepted_at)
  values (v_claim.company_id, v_claim.claimant_id, 'business_owner',
          array['listings.write.own','bookings.read.own','payments.read','reviews.reply.own'], now())
  on conflict (company_id, profile_id) do nothing;

  update profiles set role = 'business_owner'
   where id = v_claim.claimant_id and role = 'customer';

  update listing_claims
     set status = 'approved', reviewed_by = auth.uid(), reviewed_at = now(), decision_note = p_note
   where id = p_claim_id
  returning * into v_claim;

  insert into audit_logs (actor_id, actor_role, action, entity_type, entity_id, after)
  values (auth.uid(), auth_role(), 'listing_claim.approve', 'company', v_claim.company_id,
          jsonb_build_object('claim_id', p_claim_id, 'claimant', v_claim.claimant_id));
  return v_claim;
end;
$$;

-- ---------------------------------------------------------------------
-- 4. PROFILE POLICIES
-- ---------------------------------------------------------------------
drop policy if exists profiles_self_read on profiles;
drop policy if exists profiles_self_update on profiles;
drop policy if exists profiles_admin_all on profiles;

create policy profiles_self_read on profiles for select
  using (id = auth.uid() or has_permission('users.read'));

-- Role and status are pinned to their current values: they are changed only
-- by assign_role() and set_account_status(), which check the caller and
-- write an audit entry. Without this clause, self-promotion is one UPDATE.
create policy profiles_self_update on profiles for update
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and role = auth_role()
    and status = (select p.status from profiles p where p.id = auth.uid())
  );

create policy profiles_admin_read on profiles for select using (has_permission('users.read'));

-- A view of who can do what, for the admin team screen.
create or replace view role_matrix
with (security_invoker = true) as
select rp.role, p.category, p.code, p.description
from role_permissions rp
join permissions p on p.code = rp.permission
order by rp.role, p.category, p.code;

grant select on role_matrix to authenticated;

-- ---------- 0021_locations.sql ----------
-- =====================================================================
-- 0021_locations.sql — PHASE 2: the global location system.
--
-- ONE TABLE, NOT SIX
--
-- Country, region, city, district, neighborhood and POI share the same
-- attributes: slug, coordinates, timezone, SEO title, meta description, H1,
-- intro, canonical, index flag, hero image, status, ordering. Six tables
-- would mean six admin screens, six translation tables and six copies of the
-- same SEO logic — and adding a seventh level later would mean doing it all
-- again.
--
-- So this is a single self-referencing table with a `level` enum and an ltree
-- path. Breadcrumbs, ancestor queries and "everything under Sharjah" become
-- one query each, at any depth.
--
-- The existing countries/regions/cities/areas tables stay: 30 foreign keys
-- point at them and the booking engine joins on them. They remain the
-- operational tables; `locations` is the canonical hierarchy and the page.
-- Triggers keep them in step.
-- =====================================================================

create type location_level as enum (
  'country', 'region', 'city', 'district', 'neighborhood', 'poi'
);

create table locations (
  id            uuid primary key default gen_random_uuid(),
  parent_id     uuid references locations(id) on delete restrict,
  level         location_level not null,
  -- Materialised ancestry: 'uae.dubai.marina'. One query for breadcrumbs,
  -- one for every descendant, at any depth.
  path          ltree not null,
  depth         smallint not null default 0,

  -- Identity
  country_code  char(2) not null,
  location_code text,                       -- 'AE-DU', IATA, municipality code
  timezone      text not null default 'Asia/Dubai',
  latitude      numeric(10,7),
  longitude     numeric(10,7),
  centroid      geography(point, 4326),
  bounds        geography(polygon, 4326),
  radius_m      integer,

  -- Presentation
  hero_media_id uuid references media_assets(id) on delete set null,
  hero_image_url text,
  status        content_status not null default 'draft',
  display_order smallint not null default 0,
  is_featured   boolean not null default false,

  -- Indexation. `is_indexable` is the admin's intent; `listing_count` is the
  -- fact. A page is only ever indexed when both agree — see should_index().
  is_indexable  boolean not null default true,
  listing_count integer not null default 0,
  child_count   integer not null default 0,

  -- Links back to the operational tables. Nullable because a neighborhood
  -- has no counterpart, and a POI is only in points_of_interest.
  country_id    uuid references countries(id) on delete cascade,
  region_id     uuid references regions(id) on delete cascade,
  city_id       uuid references cities(id) on delete cascade,
  area_id       uuid references areas(id) on delete cascade,
  poi_id        uuid references points_of_interest(id) on delete cascade,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint locations_root_has_no_parent
    check ((level = 'country') = (parent_id is null)),
  constraint locations_coords_together
    check (num_nonnulls(latitude, longitude) <> 1)
);

create unique index locations_path_uq on locations using btree (path);
create index locations_path_gist on locations using gist (path);
create index locations_parent_idx on locations (parent_id, display_order);
create index locations_level_idx on locations (level, country_code) where status = 'published';
create index locations_centroid_gix on locations using gist (centroid);
create unique index locations_country_uq on locations (country_id) where country_id is not null;
create unique index locations_region_uq  on locations (region_id)  where region_id  is not null;
create unique index locations_city_uq    on locations (city_id)    where city_id    is not null;
create unique index locations_area_uq    on locations (area_id)    where area_id    is not null;
create unique index locations_poi_uq     on locations (poi_id)     where poi_id     is not null;

-- ---------------------------------------------------------------------
-- TRANSLATIONS
-- Every SEO field lives here, once, for every level.
-- ---------------------------------------------------------------------
create table location_translations (
  location_id      uuid not null references locations(id) on delete cascade,
  locale           locale_code not null,
  name             text not null,
  slug             text not null,
  -- H1 is separate from name and from meta title on purpose: "Dubai" is the
  -- name, "Things to Do in Dubai" is the H1, and the title tag needs the year
  -- and a call to action. Collapsing them produces pages that read like a
  -- database dump.
  h1               text,
  tagline          text,
  intro            text,
  description      text,
  body             text,
  meta_title       text,
  meta_description text,
  canonical_url    text,
  robots           text not null default 'index,follow',
  og_title         text,
  og_description   text,
  primary key (location_id, locale)
);

-- Globally unique per locale, so /destinations/{slug} resolves without
-- knowing the level — which is what the requested URL shape needs.
create unique index location_slug_uq on location_translations (locale, slug);

create trigger touch_locations before update on locations
  for each row execute function internal.touch_updated_at();

-- ---------------------------------------------------------------------
-- HIERARCHY MAINTENANCE
-- ---------------------------------------------------------------------

/**
 * Keeps `path` and `depth` correct from the parent plus this row's slug.
 * ltree labels allow only [A-Za-z0-9_], so the slug is transliterated —
 * Arabic slugs stay in the translation table where they belong.
 */
create or replace function internal.location_path_label(p_location_id uuid)
returns text
language sql stable
as $$
  select coalesce(
    nullif(regexp_replace(lower(lt.slug), '[^a-z0-9]+', '_', 'g'), ''),
    replace(p_location_id::text, '-', '')
  )
  from location_translations lt
  where lt.location_id = p_location_id and lt.locale = 'en'
  limit 1;
$$;

create or replace function internal.rebuild_location_path(p_location_id uuid)
returns void
language plpgsql security definer set search_path = public, internal
as $$
declare
  v_parent_path ltree;
  v_label       text;
  v_new_path    ltree;
  r             record;
begin
  select l.path into v_parent_path
  from locations c join locations l on l.id = c.parent_id
  where c.id = p_location_id;

  v_label := internal.location_path_label(p_location_id);
  v_new_path := coalesce(v_parent_path, ''::ltree) ||
                (case when v_parent_path is null then v_label::ltree
                      else v_label::ltree end);

  update locations
     set path = v_new_path, depth = nlevel(v_new_path) - 1
   where id = p_location_id;

  -- Moving a branch must move everything under it, or the tree lies.
  for r in select id from locations where parent_id = p_location_id loop
    perform internal.rebuild_location_path(r.id);
  end loop;
end;
$$;

create or replace function internal.location_after_translation()
returns trigger
language plpgsql security definer set search_path = public, internal
as $$
begin
  if new.locale = 'en' then
    perform internal.rebuild_location_path(new.location_id);
  end if;
  return null;
end;
$$;

create trigger rebuild_path_on_translation
  after insert or update of slug on location_translations
  for each row execute function internal.location_after_translation();

/** Ancestors, root first — the breadcrumb trail in one query. */
create or replace function location_ancestors(p_location_id uuid, p_locale locale_code default 'en')
returns table (id uuid, level location_level, name text, slug text, depth smallint)
language sql stable
as $$
  select l.id, l.level, lt.name, lt.slug, l.depth
  from locations target
  join locations l on l.path @> target.path
  join location_translations lt on lt.location_id = l.id and lt.locale = p_locale
  where target.id = p_location_id
  order by l.depth;
$$;

/** Everything beneath a location, at any depth. */
create or replace function location_descendants(
  p_location_id uuid, p_level location_level default null, p_locale locale_code default 'en'
)
returns table (id uuid, level location_level, name text, slug text, listing_count integer)
language sql stable
as $$
  select l.id, l.level, lt.name, lt.slug, l.listing_count
  from locations root
  join locations l on l.path <@ root.path and l.id <> root.id
  join location_translations lt on lt.location_id = l.id and lt.locale = p_locale
  where root.id = p_location_id
    and (p_level is null or l.level = p_level)
    and l.status = 'published'
  order by l.display_order desc, l.listing_count desc, lt.name;
$$;

-- ---------------------------------------------------------------------
-- INDEXATION GATE
--
-- The brief: do not generate millions of pages; index only locations with
-- meaningful content. A location page earns indexation by having inventory
-- or by having been written. Everything else renders for a visitor who lands
-- on it, and carries noindex,follow — crawlable, not indexed.
-- ---------------------------------------------------------------------
create or replace function should_index_location(p_location_id uuid, p_locale locale_code default 'en')
returns boolean
language sql stable
as $$
  select
    l.status = 'published'
    and l.is_indexable
    and (
      -- Either it has enough inventory to answer the query…
      l.listing_count >= 3
      -- …or someone has actually written the page.
      or coalesce(length(lt.intro), 0) >= 250
      -- Countries and regions are hubs: they earn their place by linking to
      -- children, not by holding listings themselves.
      or (l.level in ('country','region') and l.child_count >= 1)
    )
  from locations l
  left join location_translations lt on lt.location_id = l.id and lt.locale = p_locale
  where l.id = p_location_id;
$$;

/** Recounts listings and children. Cheap enough to run nightly. */
create or replace function refresh_location_counts()
returns integer
language plpgsql security definer set search_path = public
as $$
declare v_count integer;
begin
  -- A location's listing count includes everything beneath it, so a country
  -- shows the sum of its cities rather than zero.
  update locations l set listing_count = coalesce(c.total, 0)
  from (
    select anc.id, count(distinct li.id) as total
    from locations anc
    join locations descendant on descendant.path <@ anc.path
    join cities ci on ci.id = descendant.city_id
    join listings li on li.city_id = ci.id and li.status = 'published'
    group by anc.id
  ) c
  where c.id = l.id;

  update locations l set child_count = coalesce(k.total, 0)
  from (select parent_id, count(*) as total from locations
        where status = 'published' group by parent_id) k
  where k.parent_id = l.id;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------
alter table locations enable row level security;
alter table locations force row level security;
alter table location_translations enable row level security;
alter table location_translations force row level security;

create policy locations_public_read on locations for select
  using (status = 'published' or is_staff());
create policy locations_staff_write on locations for all
  using (has_permission('settings.write') or is_admin())
  with check (has_permission('settings.write') or is_admin());

create policy location_tr_read on location_translations for select using (
  exists (select 1 from locations l where l.id = location_translations.location_id
          and (l.status = 'published' or is_staff())));
create policy location_tr_write on location_translations for all
  using (has_permission('settings.write') or is_admin())
  with check (has_permission('settings.write') or is_admin());

-- ---------------------------------------------------------------------
-- READ MODEL
-- ---------------------------------------------------------------------
create or replace view location_pages
with (security_invoker = true) as
select
  l.id, lt.locale, l.level, l.path, l.depth, l.parent_id,
  lt.name, lt.slug, lt.h1, lt.tagline, lt.intro, lt.description, lt.body,
  lt.meta_title, lt.meta_description, lt.canonical_url, lt.robots,
  lt.og_title, lt.og_description,
  l.country_code, l.location_code, l.timezone, l.latitude, l.longitude,
  l.hero_image_url, l.status, l.display_order, l.is_featured,
  l.is_indexable, l.listing_count, l.child_count,
  l.country_id, l.region_id, l.city_id, l.area_id, l.poi_id,
  should_index_location(l.id, lt.locale) as should_index
from locations l
join location_translations lt on lt.location_id = l.id
where l.status = 'published';

grant select on location_pages to anon, authenticated;

-- ---------- 0022_bootstrap_setup.sql ----------
-- =====================================================================
-- 0022_bootstrap_setup.sql — first-run setup.
--
-- Creates the one route that can grant super admin, and makes it close
-- itself the moment it is used.
--
-- THE THREAT
--
-- A /setup page that grants the highest privilege on the platform is a
-- catastrophic hole if it stays reachable. Someone finds it, claims super
-- admin, and owns every booking and every traveller's details.
--
-- Four guards, and the first is the one that matters:
--
--   1. It works only while ZERO super admins exist. After the first one,
--      the function raises and the page 404s. Permanently.
--   2. An advisory lock makes the check-then-insert atomic, so two requests
--      arriving in the same millisecond cannot both succeed.
--   3. An optional SETUP_TOKEN must match if it is set — useful when the
--      site is already public before you have claimed the account.
--   4. Successes are audited here; rejections are audited by the caller,
--      because a row written before a RAISE rolls back with it.
-- =====================================================================

/**
 * True once anyone holds super_admin. Cheap enough to call on every request
 * to /setup, which is how the page knows to disappear.
 */
create or replace function is_setup_complete()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (select 1 from profiles where role = 'super_admin');
$$;

grant execute on function is_setup_complete() to anon, authenticated;

/**
 * Promotes a profile to super_admin, once, ever.
 *
 * Called with the service role from the setup action, because the person
 * running it has no privileges yet by definition — they are a brand new
 * account. That makes the internal checks the entire security boundary, so
 * they are written to fail closed.
 */
create or replace function bootstrap_super_admin(
  p_profile_id uuid,
  p_ip         text default null
)
returns profiles
language plpgsql security definer set search_path = public
as $$
declare
  v_profile profiles;
  v_existing integer;
begin
  -- Serialises every concurrent call on one key. Without it, two requests can
  -- both read "zero super admins" before either writes, and both succeed.
  perform pg_advisory_xact_lock(hashtext('bootstrap_super_admin'));

  select count(*) into v_existing from profiles where role = 'super_admin';

  if v_existing > 0 then
    -- No audit insert here. Postgres has no autonomous transactions, so a row
    -- written immediately before a RAISE is rolled back with it — the log
    -- entry would silently never exist. Rejections are recorded by the
    -- calling action instead, in its own transaction. Found by
    -- 09_bootstrap_setup.sql, which expected a rejection row and got none.
    raise exception 'Setup has already been completed. Ask an existing super admin for access.'
      using errcode = 'insufficient_privilege';
  end if;

  update profiles
     set role = 'super_admin',
         status = 'active',
         email_verified_at = coalesce(email_verified_at, now())
   where id = p_profile_id
  returning * into v_profile;

  if not found then
    raise exception 'That account does not exist' using errcode = 'no_data_found';
  end if;

  insert into audit_logs (action, actor_id, actor_role, entity_type, entity_id, after, ip)
  values ('setup.completed', p_profile_id, 'super_admin', 'profile', p_profile_id,
          jsonb_build_object('email', v_profile.email), nullif(p_ip, '')::inet);

  -- A visible record for anyone auditing the project later.
  insert into site_settings (key, value, description)
  values ('setup', jsonb_build_object('completed_at', now(), 'by', v_profile.email),
          'First-run setup. Once present, /setup is permanently closed.')
  on conflict (key) do nothing;

  return v_profile;
end;
$$;

