#!/usr/bin/env bash
# Regenerates the paste-ready setup files from the numbered migrations.
# Run after adding a migration:  bash supabase/scripts/build-setup-files.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

OUT=supabase/setup
mkdir -p "$OUT"

# The split point is not arbitrary. Supabase's SQL Editor runs a pasted script
# as ONE transaction, and Postgres refuses to USE an enum value in the same
# transaction that ADDED it. Migration 0018 adds three roles; 0019 uses them.
# So the files must break between them.
header() {
  cat <<HEADER
-- =====================================================================
-- $1
-- Generated by supabase/scripts/build-setup-files.sh — do not edit.
-- Paste into the Supabase SQL Editor and run. $2
-- =====================================================================

HEADER
}

# Everything up to and including the migration that ADDS enum values goes in
# part 1; everything from the migration that USES them goes in part 2.
SPLIT_AT=0019

: > "$OUT/part-1-schema.sql"
: > "$OUT/part-2-schema.sql"
header "PART 1 of 2 — schema up to the role enum" "Run this first." >> "$OUT/part-1-schema.sql"
header "PART 2 of 2 — permissions, auth functions and locations" "Run after Part 1 succeeds." >> "$OUT/part-2-schema.sql"

for f in supabase/migrations/*.sql; do
  name="${f##*/}"
  num="${name%%_*}"
  if [[ "$num" < "$SPLIT_AT" ]]; then target="$OUT/part-1-schema.sql"; else target="$OUT/part-2-schema.sql"; fi
  { echo "-- ---------- $name ----------"; cat "$f"; echo; } >> "$target"
done

{ header "PART 3 — seed data" "Run last. Safe to run more than once."
  cat supabase/seed/seed.sql
} > "$OUT/part-3-seed.sql"

echo "Wrote:"
wc -l "$OUT"/*.sql
