'use client';

import { useActionState } from 'react';
import { Loader2, CheckCircle2, Circle, PauseCircle } from 'lucide-react';
import { submitTourAction, setTourStatusAction, type EditorState } from '@/actions/tour-editor';

/**
 * The publish step.
 *
 * A supplier cannot publish. What they can do is submit, and the checklist
 * here is generated by `tour_completeness()` in the database — the same
 * function that gates the submission — so the UI can never tell them they're
 * ready when the server disagrees.
 */
export function SubmitPanel({
  tourId, status, score, missing,
}: { tourId: string; status: string; score: number; missing: string[] }) {
  const [state, submit, isPending] = useActionState<EditorState, FormData>(
    submitTourAction, { status: 'idle' },
  );
  const [pauseState, pause, isPausing] = useActionState<EditorState, FormData>(
    setTourStatusAction, { status: 'idle' },
  );

  const ready = score >= 80;

  return (
    <div className="flex flex-col gap-5 rounded-[var(--radius-lg)] bg-[var(--paper)] p-6">
      <div className="flex flex-col gap-1">
        <h3 className="text-[var(--text-lg)] font-semibold">Checklist</h3>
        <p className="text-[var(--text-sm)] text-[var(--ink-soft)]">
          You need 80% to submit. Our team reviews within one working day and either publishes it
          or tells you exactly what to change.
        </p>
      </div>

      <ul className="flex flex-col gap-2">
        {missing.length === 0 ? (
          <li className="flex items-center gap-2 text-[var(--text-sm)] text-[var(--teal)]">
            <CheckCircle2 className="h-4 w-4" aria-hidden /> Everything's in place.
          </li>
        ) : (
          missing.map((item) => (
            <li key={item} className="flex items-start gap-2 text-[var(--text-sm)] text-[var(--ink-soft)]">
              <Circle className="mt-0.5 h-4 w-4 shrink-0 text-[var(--ink-faint)]" aria-hidden />
              {item}
            </li>
          ))
        )}
      </ul>

      {state.status === 'error' && (
        <p role="alert" className="rounded-[var(--radius-md)] bg-[color-mix(in_oklab,var(--pomegranate)_10%,transparent)] p-3 text-[var(--text-sm)] text-[var(--pomegranate)]">
          {state.message}
        </p>
      )}
      {state.status === 'saved' && (
        <p role="status" className="rounded-[var(--radius-md)] bg-[var(--teal-wash)] p-3 text-[var(--text-sm)] text-[var(--teal-deep)]">
          {state.message}
        </p>
      )}

      <div className="flex flex-wrap gap-3">
        {['draft', 'rejected', 'paused'].includes(status) && (
          <form action={submit}>
            <input type="hidden" name="tourId" value={tourId} />
            <button type="submit" disabled={isPending || !ready}
              className="flex h-11 items-center gap-2 rounded-[var(--radius-pill)] bg-[var(--teal)] px-6 font-semibold text-white disabled:opacity-50">
              {isPending && <Loader2 className="h-4 w-4 animate-spin" aria-hidden />}
              {ready ? 'Submit for review' : `${score}% — not ready yet`}
            </button>
          </form>
        )}

        {status === 'published' && (
          /* Pausing is instant and needs no approval. An operator whose vehicle
             breaks down must be able to stop selling in one click. */
          <form action={pause}>
            <input type="hidden" name="tourId" value={tourId} />
            <input type="hidden" name="status" value="paused" />
            <button type="submit" disabled={isPausing}
              className="flex h-11 items-center gap-2 rounded-[var(--radius-pill)] border border-[var(--hairline)] px-6 font-semibold disabled:opacity-60">
              {isPausing ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> : <PauseCircle className="h-4 w-4" aria-hidden />}
              Pause selling
            </button>
          </form>
        )}

        {status === 'in_review' && (
          <p className="text-[var(--text-sm)] text-[var(--ink-soft)]">
            With our review team. We'll email you when there's a decision.
          </p>
        )}
      </div>

      {pauseState.status === 'saved' && (
        <p role="status" className="text-[var(--text-sm)] text-[var(--teal)]">{pauseState.message}</p>
      )}
    </div>
  );
}
